version: "3.9.13"

services:

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./app/models:/app/app/models
    restart: unless-stopped

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./app/models:/app/app/models
    depends_on:
      - fastapi
    restart: unless-stopped