services:

  fastapi:
    image: ghcr.io/mziaratban/egfr-stage-prediction-api-fastapi:latest
    container_name: egfr-fastapi
    restart: unless-stopped

    ports:
      - "8000:8000"

    networks:
      - app-network



  streamlit:
    image: ghcr.io/mziaratban/egfr-stage-prediction-api-streamlit:latest
    container_name: egfr-streamlit
    restart: unless-stopped

    depends_on:
      - fastapi

    ports:
      - "8501:8501"

    networks:
      - app-network



networks:

  app-network:
    driver: bridge
