name: Deploy

on:
  push:
    branches:
      - main

jobs:

  deploy:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build FastAPI
        run: |
          docker build \
          -f Dockerfile.fastapi \
          -t ghcr.io/mziaratban/egfr-stage-prediction-api-fastapi:latest .

      - name: Push FastAPI
        run: |
          docker push \
          ghcr.io/mziaratban/egfr-stage-prediction-api-fastapi:latest

      - name: Build Streamlit
        run: |
          docker build \
          -f Dockerfile.streamlit \
          -t ghcr.io/mziaratban/egfr-stage-prediction-api-streamlit:latest .

      - name: Push Streamlit
        run: |
          docker push \
          ghcr.io/mziaratban/egfr-stage-prediction-api-streamlit:latest

      - name: Deploy to Ubuntu
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/myapp
            ./deploy.sh
