name: Deploy

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
    branches:
      - main


jobs:

  deploy:

    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}


    steps:

      - name: Checkout
        uses: actions/checkout@v4


      # ------------------------------
      # Prepare deployment directory
      # ------------------------------

      - name: Prepare deployment directory
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |
            mkdir -p /opt/myapp


      # ------------------------------
      # Copy deployment files
      # ------------------------------

      - name: Copy deployment files
        uses: appleboy/scp-action@v0.1.7

        with:

          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          source: "deploy/deploy.sh,deploy/docker-compose.production.yml,prometheus,grafana"

          target: "/opt/myapp"



      # ------------------------------
      # Arrange files
      # ------------------------------

      - name: Arrange deployment files
        uses: appleboy/ssh-action@v1.0.3

        with:

          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |

            cd /opt/myapp

            if [ -d "deploy" ]; then
              mv deploy/deploy.sh .
              mv deploy/docker-compose.production.yml .
              rm -rf deploy
            fi



      # ------------------------------
      # Deploy containers
      # ------------------------------

      - name: Deploy to Ubuntu
        uses: appleboy/ssh-action@v1.0.3

        with:

          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |

            cd /opt/myapp

            chmod +x deploy.sh

            ./deploy.sh
